### ISSUE TITLE
The problem about EPS05

### ISSUE THREAD

**Issue by watsonsong** [SergeyTeplyakov/ErrorProne.NET#110]
If the readonly struct parameter need be captured by a inner delegate of the method, it ok do not add 'in' modifier.
I think it could be better to check this.

**Comment by michalfi** [comment]
There are other situation where parameter cannot be modified to "in":
- method is an iterator (uses yield) - won't compile
- method is called via dynamic dispatch - crashes at runtime

**Comment by SergeyTeplyakov** [comment]
Fixed by #197
