### ISSUE TITLE
Three different nuget packages?

### ISSUE THREAD

**Issue by memark** [SergeyTeplyakov/ErrorProne.NET#114]
There appear to be three distinct nuget packages, without any interdependencies:

- ErrorProne.NET
- ErrorProne.NET.Structs
- ErrorProne.NET.CoreAnalyzers

What are their relationsships? Which one(s) should be used? Which one is being described on the main page and in the release notes?

**Comment by memark** [comment]
Any input on this, @SergeyTeplyakov?

**Comment by SergeyTeplyakov** [comment]
Sorry for the delay:

* ErrorProne.NET is the old analyzer that I've started working on. Obsoleted by now.
* ErrorProne.NET.Structs - set of analyzers for detecting perf issues with structs, like defensive copies and such.
* ErrorProne.NET.CoreAnalyzers - a subset of analyzers from ErrorProne.NET that will be useful for most developers.

**Comment by AArnott** [comment]
Can we get this updated in the README.md for this project? It doesn't name *any* of these packages.

**Comment by memark** [comment]
Yes, please. That would be most helpful, @SergeyTeplyakov.

**Comment by sunsided** [comment]
Unlisting the legacy package at NuGet may be helpful as well.

**Comment by SergeyTeplyakov** [comment]
I unlisted all the stale nuget packages.

**Comment by SergeyTeplyakov** [comment]
And I updated readme as well. So closing for now.
