### ISSUE TITLE
EPS01 fires for a struct with assignment to this

### ISSUE THREAD

**Issue by jaredpar** [SergeyTeplyakov/ErrorProne.NET#117]
Consider the following `struct` definition:

```
struct SelfAssign {
    public readonly int Field;

    public void M(SelfAssign other) {
      this = other;
    }
}
```

This struct can't be made `readonly` due to the assignment into `this`. The EPS01 warning is incorrectly emitted here.

**Comment by SergeyTeplyakov** [comment]
Thanks a lot, @jaredpar for reporting the issue.
Working on a fix.

**Comment by SergeyTeplyakov** [comment]
@jaredpar The issue is fixed. Do you want me to publish a new version of the analyzers? (I'm going to do this anyways, but I can do this sooner if you're going to use the analyzer soon).
