### ISSUE TITLE
Should EPS05 be triggered for operators?

### ISSUE THREAD

**Issue by gpetrou** [SergeyTeplyakov/ErrorProne.NET#125]
Lets say we have the following readonly struct:

     public readonly struct Point2D
     {
         public readonly double X;
         public readonly double Y;
     }

If we have an operator like:

     public static Point2D operator *(Point2D point, double scalar) =>
            new Point2D(point.X * scalar, point.Y * scalar);

should the EPS05 be triggered in this case?
It looks like it is triggered only for methods.

**Comment by SergeyTeplyakov** [comment]
Yep, the diagnostic should be triggered here as well. Thanks for reporting!

**Comment by SergeyTeplyakov** [comment]
I removed EPS05 because with C# 8 the analyzer is not that useful.
But I added the test to show that the hidden copy analyzer works for operators.

**Comment by SergeyTeplyakov** [comment]
The test case is added by #197
