### ISSUE TITLE
EPS02 is not reported if struct contains public fields, it only works with Auto Properties

### ISSUE THREAD

**Issue by sonnemaf** [SergeyTeplyakov/ErrorProne.NET#144]
Hi,

I found a bug that EPS02 is not analyzed if the struct contains public fields. The Point struct in the followin screenshot is reported in the Foo method because it has auto properties.

![image](https://user-images.githubusercontent.com/9335559/55890200-90040680-5bb2-11e9-9755-cfa115eda5c1.png)

If you change the 'Y' auto property to a field it doesnt report EPS02 any more.

![image](https://user-images.githubusercontent.com/9335559/55890444-ff79f600-5bb2-11e9-915c-cccdf5ada000.png)

Code.

```
class Program {
        static void Main(string[] args) {
            Foo(new Point(1, 2));
        }

        static void Foo(in Point p) {
        }
    }

    struct Point {

        public long X { get; set; }
        public long Y;

        public Point(long x, long y) {
            this.X = x;
            this.Y = y;
        }

        public override string ToString() {
            return $"({X.ToString()},{Y.ToString()})";
        }
    }
```

**Comment by SergeyTeplyakov** [comment]
This is by design. 

In pre-C# 8 world there was a huge difference between fields and properties access in readonly contexts: accessing a field for a struct passed by in never caused a defensive copy, but accessing a property was causing it.

So the analyzer repsected this logic: if a struct is a POCO struct (i.e. a struct that has a bunch of public fields and no methods/properties), then the struct was safe for passing by `in` because it was very hard to misuse it and cause a bunch of copies. But if the struct has a bunch of properties, then passing it by `in` was not wise, because accessing the properties was causing a copy.

Things hasve changed in C# 8, because now an auto-property getter is implicitly marked with `IsReadOnly` attribute and the access to that property in "readonly" context is no longer causes a defensive copy.

I've changed the analyzers to respect the new behavior and because now it's much safer to access auto properties I'm going to completely remove EPS02

**Comment by sonnemaf** [comment]
I don't think you should remove EPS02 and close this issue.

Defensive copies are still made, also in C# 8.0.

Please open the following code in [SharpLab.io](https://sharplab.io/#v2:D4AQTAjAsAULB2BDAtgUwM4AdEGNUAIBhAe3nWIBtUBBTTCAZgBZ8BvWfT/cbiAdjYcuwkBABs3FgFlEAS3gAKUQAYA2gF18iAE4BzdAEpBMYaa4AxYsQXxUAd3wAFYvIAuAZVfaArjlcKGABomAwMAbiEzAF9YSNNRCRAWS2t5Jxd4Dy9fV3xMI3YTM3iIAE4FTAA6ABViT215XQVQiKLirlFyqoANcLj2qvc7RExm1vaRMorKgBFZdFc+tonO6dr6xual9pjl3djlhZ8/dLd6nON+joZ8ClJdfG62fF1UVzD8dDeP3faQG7u8AeAE1nq93p9vvh9ssRDdnGdsn4FICHgAPQK3e74ACeBSuZlcAAt5pUngBefBo8YTTjE0mgyk4mnRA5/G5JfBDEbNYy0ukk9D4Sm2BwIzLnZH09CVYGY6Vk7bFGHs/AAE2I3gARlR8HMFsKAHz4GTEyruACO2n8CieACpHkYANT4BSgh3Alps4r/fDEABuqG0DTVBBU+HWXk2RnJxoAJAAiBSsbo1OpRoHNKKBVjAtMbTMGKIGBMs6EHXZAA==)

The size of the mutable PointStruct is 16 bytes, that is larger than IntPtr.Size. According to the [docs](https://docs.microsoft.com/en-us/dotnet/csharp/write-safe-efficient-code) the Foo() method should use an in-parameter.

You will see that the ToString(), Swap() methods and the Dist property calls are still causing defensive copies. I have marked them in purple in the next screenshot. You are right that the Property X (get) is not doing this any more.

![image](https://user-images.githubusercontent.com/9335559/81905040-75297000-95c4-11ea-8e9a-6061eb953f1b.png)

```
using System;

namespace ConsoleApp134 {
    class Program {
        static void Main(string[] args) {
            Console.WriteLine("Hello World!");
        }

        static void Foo(in PointStruct p) {
            Console.WriteLine(p.ToString());
            Console.WriteLine(p.X);
            p.Swap();
            Console.WriteLine(p.Dist);
            Console.WriteLine(p.ToString());
        }
    }


    struct PointStruct {

        public long X { get; set; }
        public long Y { get; set; }

        public PointStruct(long x, long y) {
            this.X = x;
            this.Y = y;
        }

        public void Swap() {
            this = new PointStruct(this.Y, this.X);
        }

        public double Dist => Math.Sqrt((X * X) + (Y * Y));

        public override string ToString() => $"({X.ToString()},{Y.ToString()})";
    }

}
```

The ToString() method and Dist property should have been marked (by me) as a C# 8 Readonly Member. this would prevent it. The Swap should have been rewritten to return a Point and not change 'this', it can than also become a readonly member.

```
struct PointStruct {

    public long X { get; set; }
    public long Y { get; set; }

    public PointStruct(long x, long y) {
        this.X = x;
        this.Y = y;
    }

    public readonly PointStruct Swap() {
        return new PointStruct(this.Y, this.X);
    }

    public readonly double Dist => Math.Sqrt((X * X) + (Y * Y));

    public readonly override string ToString() => $"({X.ToString()},{Y.ToString()})";
}
```

As you can see in [SharpLab.io](https://sharplab.io/#v2:D4AQTAjAsAULB2BDAtgUwM4AdEGNUAIBhAe3nWIBtUBBTTCAZgBZ8BvWfT/cbiAdjYcuwkBABs3FgFlEAS3gAKUQAYA2gF18iAE4BzdAEpBMYaa4AxYsQXxUAd3wAFYvIAuAZVfaArjlcKGABp8JgMDAG4hMwBfWCjTUQkQFktreScXeA8vX1d8TCN2EzMEiABOBUwAOgAVYk9teV0FMMjikq5RCuqADQj4jur3O0RMFraOkXLKqoARWXRXfvbJrpm6hqaW5Y7Ylb24lcWfPwy3BtzjAc6GfApSXXwetnxdVFdw/HR3z72OkFu93gjwAmi83h8vj98AcViJbs5zjk/AogY8AB7BNH4ACehWuZlcAAsFlVngBefDoiaTTjE0lgyk4mkxQ7/W7aVCIAAmpAoOLOWQup2GoxaxlpnBAAlsDkRQuR/np6CqIOCyrJOxKsPZ+E5PL5At53gARlR8PNFvhyQA+fAyYlVdwAR20/gUzwAVE8jABqfAKMHekGtNklAF6rm8+D8/DEABuqG0jW5BBU+A2Xi2Rlt+AAJAAiBSsHq1epZ4EtaKBVggsubSsGaIGAssmGHPZAA==) all defensive copies in the Foo() method are now gone.

![image](https://user-images.githubusercontent.com/9335559/81905644-44960600-95c5-11ea-92df-07995f2527be.png)

Please do not just remove EPS02. There is still a purpose for it when you call non readonly members.

Writing mutable structs with Auto Properties and not using Fields is a bad idea. But that's a totally different story. 

```
struct PointStruct {

    public long X;
    public long Y;

    public PointStruct(long x, long y) {
        this.X = x;
        this.Y = y;
    }

    public readonly PointStruct Swap() {
        return new PointStruct(this.Y, this.X);
    }

    public readonly double Dist => Math.Sqrt((X * X) + (Y * Y));

    public readonly override string ToString() => $"({X.ToString()},{Y.ToString()})";
}
```

**Comment by sonnemaf** [comment]
Second thoughts. You are maybe right by removing the EPS02. But please generate the EPS06 for all hidden copies. This would be on line 10, 12, 13 and 14 in the next screenshot.

![image](https://user-images.githubusercontent.com/9335559/81910026-bb360200-95cb-11ea-91fd-4e2b1710dbe4.png)

**Comment by SergeyTeplyakov** [comment]
The analyzer already emits all the diagnostics:

![image](https://user-images.githubusercontent.com/726448/82009768-0fb99b80-9625-11ea-9a70-555f74685222.png)

But one thing to note: the defaults right now 24 bytes. So I added 2 more fields (even though only one field was required) in order to trigger them. But as I already mentioned, there is an editor config setting to change the defaults.

**Comment by sonnemaf** [comment]
I didn't know that you made EPS06 size related. 

I still have some questions.
- Can you tell me what the editor config setting is? 
- Is it also already in 0.3.0-beta.0 version?
- Why have you chosen for 24 bytes? Wouldn't more than IntPtr.Size be better? I'm not sure. I'm just very interested in your motivation.
- Are you also planning to drop EPS03 and EPS04
- I really like this analyzer. Shouldn't this be included in Roslyn? Similar to CS8656 (screenshot below).

![image](https://user-images.githubusercontent.com/9335559/82028067-6f4f8f80-9695-11ea-9a0c-ab7ffcf61b9f.png)
