### ISSUE TITLE
Incorrect warnings about nullable parameters

### ISSUE THREAD

**Issue by gpetrou** [SergeyTeplyakov/ErrorProne.NET#146]
Currently, we get warnings about using the in-modifier with Nullable parameters. https://github.com/SergeyTeplyakov/ErrorProne.NET/blob/master/src/ErrorProne.NET.StructAnalyzers/TypeExtensions.cs#L28
However, asking about it in https://github.com/dotnet/docs/issues/11834 it seems that this is not correct.

**Comment by SergeyTeplyakov** [comment]
Fixed in master.
