### ISSUE TITLE
Wrong warning for ReadOnlySequence

### ISSUE THREAD

**Issue by aliveli186** [SergeyTeplyakov/ErrorProne.NET#148]
The following warning is wrong.:
`Non-readonly struct 'ReadOnlySequence' used as in-parameter...`

The source code of ReadOnlySequence shows that it's indeed readonly struct.

![ErrorProne_bug](https://user-images.githubusercontent.com/8914034/62367202-93d8e180-b531-11e9-87f6-e68f7ab1b068.png)

**Comment by SergeyTeplyakov** [comment]
Fixed by #189
