### ISSUE TITLE
Offer to contribute some analyzers

### ISSUE THREAD

**Issue by leotsarev** [SergeyTeplyakov/ErrorProne.NET#154]
Hi, I have created some analyzers https://github.com/leotsarev/hardcode-analyzer that I still willing to support, but want to join some larger project to get more visibility and to share i.e. build infrastructure.

I'm propose to contribute ErrorProne.Hardcode that has following rules:
1. Prohibited to hardcode URIs in application code. Based on https://github.com/leotsarev/hardcode-analyzer/blob/master/Tsarev.Analyzer.Hardcode.Url/UrlHardcodeAnalyzer.cs
2. Prohibited to hardcode emails in application code. Based on https://github.com/leotsarev/hardcode-analyzer/blob/master/Tsarev.Analyzer.Hardcode.Email/EmailHardcodeAnalyzer.cs

**Comment by SergeyTeplyakov** [comment]
Hi Leonid,

Thanks a lot for your interest, but I envisioned that ErrorProne.NET should be all about code correctness, and, maybe, about performance.

But the 2 analyzers that you suggested are quite application-specific from my point of view.

Don't get me wrong, I think the analyzers you've written are useful, but I'm not sure it make sense to glue them together with ErrorProne.

The same is true for the ErrorProne analyzers themselves. They're useful, but I don't think it would be a good idea to include them, for instance, with stylecop or fxcop analyzers. They're just different.

**Comment by leotsarev** [comment]
Ok, no big feelings, thanks for your work!
