### ISSUE TITLE
Warn when using OrderBy on ConcurrentDictionary

### ISSUE THREAD

**Issue by jbayardo** [SergeyTeplyakov/ErrorProne.NET#155]
This triggers a subtle race condition that causes an exception to be thrown, see: https://stackoverflow.com/questions/11692389/getting-argument-exception-in-concurrent-dictionary-when-sorting-and-displaying

**Comment by SergeyTeplyakov** [comment]
Other non-thread safe methods are: 'ToArray', 'ToList', 'OrderByDescending', 'Reverse'.

**Comment by SergeyTeplyakov** [comment]
Fixed.
