### ISSUE TITLE
Wrong segnalation when using an extension method on a non-readonly struct as in parameter

### ISSUE THREAD

**Issue by mnznndr97** [SergeyTeplyakov/ErrorProne.NET#198]
Hi, I' ve found a strange behavior with the analyzer in the case that a non-readonly struct passed as **in** parameter is used with an extension method that accepts the same **in** parameter.

Here there is an example. I' m using the latest 0.3.0-beta.0 NuGet package

![image](https://user-images.githubusercontent.com/44756553/82639866-e04cf500-9c09-11ea-9a0e-715c4ba7d3a5.png)

As you can see in the image, if I use the extension method, the analyzer tells me that there would be a defensive copy, but if I directly use the static method there are no warnings.
The struct is non-readonly but it has only public fields so there should' t be any defensive copy.

Looking at the IL (confirmed also by the disassembly), `OtherStuffStaticCall` and `OtherStuff` are compiled to 

```
void OtherStuff (
            [in] valuetype SomeStruct& str
        ) cil managed
{
...

IL_0000: ldarg.0
IL_0001: call bool Extension::Is42(valuetype SomeStruct&)
IL_0006: pop
IL_0007: ret

}
```
so no defensive copy is applied

Here there is a gist of the code
[https://sharplab.io/#gist:d0d2feef2a6289815458cd7440471c16](https://sharplab.io/#gist:d0d2feef2a6289815458cd7440471c16)

**Comment by SergeyTeplyakov** [comment]
I've added the test case and here is the gif from the extension from master:


![BugFix](https://user-images.githubusercontent.com/726448/83097139-3aabe280-a05c-11ea-93b9-f4c0499f580d.gif)

**Comment by SergeyTeplyakov** [comment]
The PR that has the test is #197.
