### ISSUE TITLE
The Visual Studio extension version is old

### ISSUE THREAD

**Issue by MatthewL246** [SergeyTeplyakov/ErrorProne.NET#212]
Currently, the Visual Studio extension (https://marketplace.visualstudio.com/items?itemName=SergeyTeplyakov.EPNS01) is an old version. Please either update the extension or note on the marketplace page that it is deprecated in favor of NuGet.

**Comment by SergeyTeplyakov** [comment]
I decided to completely remove it in favour of just normal nuget packages.
