### ISSUE TITLE
EPS11: false positive on classes?

### ISSUE THREAD

**Issue by shuebner** [SergeyTeplyakov/ErrorProne.NET#226]
Hi all,
EPS11 will trigger when `ImmutableArray<>` or a struct marked as non-defaultable is used as a field in a class.
Do I misunderstand the use-case or is this a false positive?

I have created a PR with two test cases and a quick fix.
The fix avoids the false positives.
Unfortunately, the fix will also prevent previously reported correct warnings, such as on class members that are not guaranteed to be initialized, e. g. in classes with a non-private default constructor and no member initializer for the member in question.

I do not have the time to get more deeply into when a warning should be reported.
I just did not want to get a warning on every class that uses ImmutableArray ;-).

**Comment by SergeyTeplyakov** [comment]
Noticed that as well. It should be totally fine to embed non-defaultable structs into classes.

**Comment by SergeyTeplyakov** [comment]
Fixed by #237.
