### ISSUE TITLE
False positives

### ISSUE THREAD

**Issue by Djoums** [SergeyTeplyakov/ErrorProne.NET#229]
Not sure if those issues have been fixed already, I can't install any prerelease due to an error.

TimeSpan is not considered a readonly struct by the analyzer :

![ErrorProne1](https://user-images.githubusercontent.com/17812393/131952527-b5030f0a-421a-441c-b6ed-3acfcf195004.png)

Nullables are somehow considered readonly structs by the analyzer :

![ErrorProne2](https://user-images.githubusercontent.com/17812393/131952604-c49f4d4f-6e76-4032-8d8a-2ff5a69a0374.png)

EPS06 seems to trigger randomly (probably related to the non-detection of a struct being readonly) :

![Sans titre](https://user-images.githubusercontent.com/17812393/131953572-b2e5b63b-802a-47b0-9481-0d34c2762221.png)

**Comment by SergeyTeplyakov** [comment]
I'm alsmost sure that all of these were fixed. What error are you getting trying to install any pre-release version of the analyzers?

**Comment by SergeyTeplyakov** [comment]
I assume @Djoums  you mentioned the installation issue here #222. I'm looking why its failing...

**Comment by Djoums** [comment]
Yes I was able to bypass the error somehow and the false possitives are gone 👍
