### ISSUE TITLE
ErrorProne.NET says that "readonly ref structs" are "Non-readonly"

### ISSUE THREAD

**Issue by Aniobodo** [SergeyTeplyakov/ErrorProne.NET#241]
ErrorProne.NET.Structs 0.1.2
What is going on here?
ErrorProne.NET says that System.ReadOnlySpan, System.Span and any other "readonly ref structs" are "Non-readonly".
Does anyone know the reason behind this?

**Comment by SergeyTeplyakov** [comment]
I'm not sure what's the point of opening a bug using such an old version, tbh. A bunch of stuff was fixed after that and, yes, in that old version it was a bug that caused this issue. It is fixed in the newer versions.

**Comment by Aniobodo** [comment]
Sorry  SergeyTeplyakov. I grabbed version 0.1.2 which is the latest on nugget.
