### ISSUE TITLE
EPC12 creates diagnostic with description "bar"

### ISSUE THREAD

**Issue by shuebner** [SergeyTeplyakov/ErrorProne.NET#246]
Version: 0.1.2 and 0.4.0-beta.1 alike

When only observing the Message property of an exception, VS shows a strange message "bar" from EPC12:
![image](https://user-images.githubusercontent.com/1770684/138645145-fb63370f-747b-4fc2-9283-a11c4c55e0af.png)

This can even show up in the error list:
![image](https://user-images.githubusercontent.com/1770684/138644718-d05b0e09-4857-4c0f-8c6e-c88b9cfbf903.png)

Also note that in the first screenshot, we get two diagnostics. The second one references a non-existing line number 22.

Could this be some foo/bar/baz code left behind somewhere? I already searched for "bar" in this repo and the roslyn and roslyn-analyzer repos, but could not find any plausible usages.

**Comment by SergeyTeplyakov** [comment]
Closing this issue, since the new version was released with the fix.
