### ISSUE TITLE
Violations show up on generated code

### ISSUE THREAD

**Issue by tiesmaster** [SergeyTeplyakov/ErrorProne.NET#253]
We've started to use the [generated HTTP clients](https://devblogs.microsoft.com/dotnet/generating-http-api-clients-using-visual-studio-connected-services/) that uses [NSwag](https://github.com/RicoSuter/NSwag) to generate a typed client, and EPS01 "Struct 'ObjectResponseResult' can be made readonly" is showing up on the generated code. Is it intentional that  ErrorProne.NET doesn't ignore generated code? I think usually generated code is excluded, but it looks like this project opts in to that. I think [this line](https://github.com/SergeyTeplyakov/ErrorProne.NET/pull/168/files#diff-1a72bd75fd80b77eacb7dcc034fadbd919a4b04da39be96521cadb15c6dd0715R36) enabled that for the given analyzer, and was added by @sharwell, so I'm looping him also him. Maybe, he can shine some light on this decision.

# Repro
Just add  ErrorProne.NET.Structs, and add a connected service. This is how I managed to get it reproduced in a new project:

1. Create a new console project
2. Add  the ErrorProne.NET.Structs package
3. Add a connected service according to the [blog post](https://devblogs.microsoft.com/dotnet/generating-http-api-clients-using-visual-studio-connected-services/), I've used the [`petstore.json`](https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/examples/v3.0/petstore.json) example from the OpenAPI repo
4. Build the project, to ensure that the `petstoreClient.cs` file is generated

This should result in `EPS01`: "Struct 'ObjectResponseResult' can be made readonly" @`petstoreClient.cs:256`

**Comment by sharwell** [comment]
> I think this line enabled that for the given analyzer, and was added by @sharwell, so I'm looping him also him. Maybe, he can shine some light on this decision.

My change was to make the current behavior explicit instead of implicit (generated code is included by default if `ConfigureGeneratedCodeAnalysis` is not called). Someone will need to consider the overall application impact if these change.

Note that EPS01 may be a candidate for a global suppression approach, especially for cases where the type is `public` or the assembly has any IVTs.

**Comment by molinch** [comment]
@tiesmaster how did you solve it?

We have a bunch of these popping:
![Image](https://github.com/user-attachments/assets/39455908-f546-4383-bdfe-122325960d20)

And we should really not care about the generated code

**Comment by molinch** [comment]
For whoever wants a solution, this is it:
1. Have a Directory.Build.props
2. Put there <Compile Include="..\GlobalSuppressions.cs" Link="GlobalSuppressions.cs" />
3. In the Global Suppression file, have for example:
```
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage(
    "Performance", "EPS06:Hidden struct copy operation",
    Justification = "Never run on Regex generated code",
    Scope = "namespaceanddescendants",
    Target = "~N:System.Text.RegularExpressions.Generated")]
```

**Comment by tiesmaster** [comment]
@molinch TBH I'm not sure if I actually solved it back then, but nowadays, I'm working in a different ecosystem, so it's not relevant anymore.

Good to hear that you managed to solve it like that 👍
