### ISSUE TITLE
Warn on async void methods

### ISSUE THREAD

**Issue by SergeyTeplyakov** [SergeyTeplyakov/ErrorProne.NET#36]
Consider the following case:

```csharp
public void Run(Action<int> a) {
  a();
}

try
{
  Run(async n => Parse(n));
}
catch(Exception) {}
```

This method will crash the app. This issue is very hard to spot.

**Comment by sharwell** [comment]
I recommend leaving the implementation of this rule to [Microsoft/vs-threading](https://github.com/Microsoft/vs-threading) analyzers. Rules previously in [DotNetAnalyzers/AsyncUsageAnalyzers](https://github.com/DotNetAnalyzers/AsyncUsageAnalyzers) have already been consolidated there.

**Comment by SergeyTeplyakov** [comment]
Already implemented in master.
