### ISSUE TITLE
Warnings about copying of TimeSpan/DateTime/CancellationToken

### ISSUE THREAD

**Issue by leotsarev** [SergeyTeplyakov/ErrorProne.NET#48]
I think it should be okay to copy small (64-bits) struct, shoudn't it?

**Comment by SergeyTeplyakov** [comment]
There two places when the size can be considered: 
1. To pass a struct by 'in' and
2. To show that the hidden copy occurred.

I've changed the rules for (1) not to emit a diagnostics for small structs, but today the size is not considered for (2).

The main reason for that is that I wanted to see where these hidden copy occurred, but I agree that it makes no sense, in general, to warn for a hidden copy for a small struct.

I'll change the (2) to not issue a diagnostic for a small structs.

**Comment by SergeyTeplyakov** [comment]
Fixed: no issues on small structs.
