### ISSUE TITLE
[Question] Why does "Expression 'ToTuple' causes a hidden copy of a struct 'Int32'" appear here? Can't find copy in IL.

### ISSUE THREAD

**Issue by aensidhe** [SergeyTeplyakov/ErrorProne.NET#53]
Code is in attachment. [I can't find any hidden copies in IL.](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQBMQGoA+ABADAAmwEYBuAWAChLsBmQogNkICZ8BRfAb0v18LuJMAahAA2AVzgAVcQAdRcADxSAfPikB7GfKWqAFDAAWASyjr8ANzGSAlPgC8akROlyFAOgDCCOBHh6rFxtyCgBfagFWTy4ePlpCABZ8AFk9O24KPiz1OFg9AFZg2N5wzL5i/kScvOMAOxh8Y3SKrKsEfAgHRvdNbQU0kOy+Tvt2Hq03OD0mwaGOrudJPrgvHz8pmYrSrMpQoA==)

[HiddenCopy.zip](https://github.com/SergeyTeplyakov/ErrorProne.NET/files/1973974/HiddenCopy.zip)

**Comment by aensidhe** [comment]
Then it still strange. If we will look on code above, we'll get:

````
        var a = i.ToTuple(); // warning here
        a = E.ToTuple(i); // no warning here
        a = ValueTuple.Create(i); // no warning here
````

As we can see `ValueTuple.Create` does not have in or ref modifiers on arguments.

**Comment by SergeyTeplyakov** [comment]
I definitely see why this can be confusing, but this is by design.

I want to show the "hidden" struct copies, not every possible copy that is more or less obvious for method calls.

For instance, just by reading the code it is hard to tell whether `foo.Bar()` is an extension method or an instance method. When you see `Bar(foo)` then it is way more obvious that the `foo` is passed somewhere and that it is very likely that the normal copy will occur (unless the `Bar` takes the first argument by 'in').

This is very similar to "hidden" allocations analyzer that I would like to write. The analyzer won't warn on `new FooBar()` but will warn on `fooBar.GetType()` (when `fooBar` is an instance of a struct).

**Comment by aensidhe** [comment]
Can I disable on callee basis then? Because we use ToTuple for readability reasons for both value and ref types. I would like to not suppress this warning globally per project, just for one extension method.

**Comment by SergeyTeplyakov** [comment]
I don't know how to disable this specific case, but I have another idea: in most cases the warnings are limited to structs with the size >= 16. But I've noticed that this specific analysis warns for small structs as well.

I'll use the same threshold here and you won't see a warning on the 'int' but still see the warning if an extension method is called on a large struct.

Will it "solve" your issue?

**Comment by SergeyTeplyakov** [comment]
Created an issue: #54.

**Comment by aensidhe** [comment]
I thought about it a couple of days and I don't think that you should do this (only, maybe for consistency with other analyzers). I'll manage without it some way or another. It's very good library, helped me a lot.

Can we think about putting some settings into `.editorconfig` in theory for that limits? E.g. someone (like me) will put up a PR? Or, may be even special attribute to disable analysis based on callee?

**Comment by SergeyTeplyakov** [comment]
I think I'll want to avoid the warning for the small structs for consistency reasons.

Regarding `.editorconfig`: I'll have no clue so far (never looked at that) how to configure an analyzer. Maybe `.editorconfig` is the right place, in this case I'll go with it, definitely. And attributes is another approach as well that is simple and doable.

I was thinking about using attributes to control the analyzers anyway. Not for this set of analyzers, but for memory analyzers to detect closure analyzers and other stfuff.

**Comment by Gav-Brown** [comment]
Hi, the only problem with this warning is you can't turn it off unless you use `[SuppressMessage]` etc. at all your call sites. You can't add `in` for an `int` extension method, for example, as then the compiler complains that `int` is not a `readonly` struct. Agree I can make an explicit method call, but that seems overkill. Unless I've missed something?

**Comment by SergeyTeplyakov** [comment]
The analyzers in the current master do not emit any diagnostics for small structs (which is 3 * sizeof(long) by default) and we do have an ability to change that size from .editorconfig (thanks to #185).
