### ISSUE TITLE
EPS02 - false positive for readonly structs from referenced library

### ISSUE THREAD

**Issue by Amarok79** [SergeyTeplyakov/ErrorProne.NET#58]
I have a library that introduces a readonly struct. Now, in a second library using the first one, EPS02 blames about using that struct with in modifier, saying the struct isn't readonly, although it is.

I guess you have to check whether external structs have the `System.Runtime.CompilerServices.IsReadOnlyAttribute`.

**Comment by SergeyTeplyakov** [comment]
Fixed and I opened the bug in Roslyn about an inability to check that a struct is [readonly](https://github.com/dotnet/roslyn/issues/27061).
