### ISSUE TITLE
Support for `DebuggerDisplay` attribute

### ISSUE THREAD

**Issue by SergeyTeplyakov** [SergeyTeplyakov/ErrorProne.NET#7]
Warn if the method is not presented or could not be found, or return value is not string etc.

**Comment by KirillOsenkov** [comment]
I wish we had this! See here:
https://github.com/Microsoft/msbuild/issues/610

It shouldn't be hard to verify that the names inside { } bind successfully.

**Comment by SergeyTeplyakov** [comment]
Yep, implementation is not that hard. Will do it soon!

**Comment by SergeyTeplyakov** [comment]
Implemented this analysis. More information could be found at https://github.com/SergeyTeplyakov/ErrorProne.NET/wiki/DebuggerDisplayAttribute-analyzer
