### ISSUE TITLE
StructAnalyser: Detect in-extension methods do not cause defensive copies

### ISSUE THREAD

**Issue by Voidzer0** [SergeyTeplyakov/ErrorProne.NET#78]
First of all: Thank you for this very helpful analyser tool!
We spotted a small shortcoming of the analyser, where it warns about hidden defensive copying where none should happen.
In our project we use structs with fields only (no methods nor properties).
Writing fields in readonly context (ref readonly / in) is prohibitted by the compiler and reading fields does not cause defensive copies, only calling properties or methods causes this.
So we are using in-extension methods, to implement (readonly) methods that do not cause defensive copying.
But the StructAnalyser warns about them as it does about normal methods/properties.

Example 1 (causes hidden defensive copy):
---------------
```cs
struct Struct
{
 public int X;
 public int Squared() => X * X;
}
class Test
{
  void doSomething(in Struct s)
  {
    s.Squared(); // <- hidden defensive copy happens, since Squared is a normal method that could modify this struct
  }
}
```

Example 2 (causes no hidden defensive copy):
---------------
```cs
struct Struct
{
 public int X;
}
static class StructExtensions
{
  public static int Squared(in this Struct s) => s.X * s.X;
}
class Test
{
  void doSomething(in Struct s)
  {
    s.Squared(); // <- no hidden defensive copy happens, since Squared is an in-extension method only accessing fields readonly, which can not modify the struct
  }
}
```

If possible, it would be nice if the StructAnalyser could grasp this difference and not warn about in-extensions, but rather only if ref-extension methods, real methods or properties are called in readonly context.

Cheers!
Keep up the good work =)

**Comment by SergeyTeplyakov** [comment]
Thanks @Voidzer0 for reporting the issue. I thought that I've fixed this, but I'll double check.

**Comment by SergeyTeplyakov** [comment]
It seems that the bug was fixed and I just need to republish analyzers with the fix.

I'm working on automated deployment process and once it's done (hopefully this week) the new version will be published.

**Comment by Voidzer0** [comment]
Thanks a lot for taking a look so quickly!
We are using in-extension methods quite a lot to avoid hidden struct copies and this issue made it hard to see the real hidden copy issues in between the harmless ones.
Once the fix is deployed ErrorProne.NET will be even more useful for us.
I am looking forward to the release.

Thank you so much for all your work on this nifty analyser!

**Comment by SergeyTeplyakov** [comment]
Published here: https://www.nuget.org/packages/ErrorProne.NET.Structs/0.1.1.10

**Comment by Voidzer0** [comment]
Thanks a lot, I'll check it out.
I'd wish Intelisense warned by default about these things.
Anyway nice work!

**Comment by SergeyTeplyakov** [comment]
CLosing the issue. Consider this was fixed.
