### ISSUE TITLE
EPS06 for ImmutableArray.ToArray

### ISSUE THREAD

**Issue by Mike-EEE** [SergeyTeplyakov/ErrorProne.NET#85]
I am getting this warning for `ImmutableArray` -- probably the most frustrating struct of all .NET because of issues such as these and so many others.  ANYWHOO 😆

From reading [this issue](https://github.com/SergeyTeplyakov/ErrorProne.NET/issues/53), the problem seems to be that a defensive copy is made as a result of passing the variable in (by value) to the extension method.

Is there a suggested workaround for this issue, by chance?  FWIW, using `ImmutableArrayExtensions.ToArray(array)` gets rid of the message for me, but I am not sure if that is because that legitimately fixes the problem or if the analyzer is not looking for that. :)

**Comment by SergeyTeplyakov** [comment]
I believe the issue is fixed already.
The new package is published: https://www.nuget.org/packages/ErrorProne.NET.Structs/0.1.1.10

**Comment by Mike-EEE** [comment]
Your belief is indeed well-grounded! 😂  Really nice work here.  Ideally, we can get #57 addressed and move to some smooth sailing. 👍
