### ISSUE TITLE
NuGet should add 'developmentDependency="true"' attribute to packages.config

### ISSUE THREAD

**Issue by Gav-Brown** [SergeyTeplyakov/ErrorProne.NET#93]
When adding the '**ErrorProne.NET.Structs**' packages to a solution, **packages.config** should have the 

`developmentDependency="true" `

attribute e.g.

`<package id="ErrorProne.NET.Structs" version="0.1.1.10" targetFramework="net472" developmentDependency="true" />`

Compare to FXCopAnalysers and StyleCop.Analysers.

**Comment by SergeyTeplyakov** [comment]
Thanks. Will change the package.
