### ISSUE TITLE
ErrorProne.NET.Structs rules appears as ESP04 instead of EPS04 in ruleset file

### ISSUE THREAD

**Issue by Gav-Brown** [SergeyTeplyakov/ErrorProne.NET#94]
Edit the ruleset in Visual Studio. Look at generated .ruleset file

`<Rule Id="ESP04" Action="Error" />`

All other rules are in the form EPS**

**Comment by SergeyTeplyakov** [comment]
Looks like a typo:). Thanks, will fix it.
